#!/bin/bash
set -e

python -m PyInstaller --noconfirm --clean --noconsole --name Medoctor --icon=res/image.icns \
  --add-data "conclusion_form/res:conclusion_form/res" \
  --add-data "search_form/input:search_form/input" \
  --add-data "analyschecker_form/input:analyschecker_form/input" \
  main.py